[tools]
bat = "latest"
eza = "latest"
fzf = "latest"
ghq = "latest"
ripgrep = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
github-cli = "latest"
gum = "latest"
pre-commit = "latest"
uv = "latest"
jq = "latest"

# [settings]
# experimental = true
# 
# [settings.python]
# uv_venv_auto = true
